export const QUERY_KEY = {
  GET_LIST_CATEGORY: "GET_LIST_CATEGORY",
  GET_LIST_MEDICAL_BOOKING_FORMS: "GET_LIST_MEDICAL_BOOKING_FORMS",
  GET_LIST_HOSPITALS: "GET_LIST_HOSPITALS",
  GET_HOSPITAL_BY_ID: "GET_HOSPITAL_BY_ID",
  GET_SPECIALTY_BY_HOSPITAL_ID: "GET_SPECIALTY_BY_HOSPITAL_ID",
  GET_DOCTOR_BY_SPECIALTY_ID: "GET_DOCTOR_BY_SPECIALTY_ID",
  GET_SERVICE_BY_HOSPITAL_ID: "GET_SERVICE_BY_HOSPITAL_ID",
  GET_SERVICE_BY_ID: "GET_SERVICE_BY_ID",
};
