import apiAuthRequest, {IGetMeResBody} from "@/apiRequest/ApiAuth";
import {handleErrorApi} from "@/apiRequest/ErrorMessage/errors";
import {AT_COOKIE_NAME} from "@/apiRequest/common";
import AppProvider from "@/app/(home)/AppProvider";
import DashBoardLayout from "@/components/Layout/DashBoardLayout";
import {Toaster} from "@/components/ui/toaster";
import type {Metadata} from "next";
import {Manrope} from "next/font/google";
import {cookies} from "next/headers";
import "../global.scss";

const manrope = Manrope({
  weight: ["300", "400", "500", "700", "800"],
  subsets: ["vietnamese"],
});

export const metadata: Metadata = {
  title: "Medpro | Phần mềm đăng ký khám chữa bệnh online",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const access_token = cookieStore.get(AT_COOKIE_NAME);
  let user: IGetMeResBody["data"] | null = null;
  try {
    if (access_token) {
      const data = await apiAuthRequest.getMeFromNextServerToServer(
        access_token?.value
      );
      user = data?.payload?.data;
    }
  } catch (error) {
    handleErrorApi({error});
  }
  return (
    <html lang="en">
      <body className={manrope.className}>
        <AppProvider initialAccessToken={access_token?.value} user={user}>
          <DashBoardLayout>{children}</DashBoardLayout>
          <Toaster />
        </AppProvider>
      </body>
    </html>
  );
}
