import DashBoardLayout from "@/components/Layout/DashBoardLayout";
import type {Metadata} from "next";
import {Manrope} from "next/font/google";
import "../global.scss";

const manrope = Manrope({
  weight: ["300", "400", "500", "700", "800"],
  subsets: ["latin", "vietnamese"],
});

export const metadata: Metadata = {
  title: "Medpro | Phần mềm đăng ký khám chữa bệnh online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <DashBoardLayout>{children}</DashBoardLayout>
      </body>
    </html>
  );
}
